import React from 'react';
import { X } from 'lucide-react';
import { InterviewSession } from '../types';
import ReactMarkdown from 'react-markdown';

interface InterviewReportModalProps {
  interview: InterviewSession;
  onClose: () => void;
}

const InterviewReportModal: React.FC<InterviewReportModalProps> = ({ interview, onClose }) => {
  return (
    <div 
      className="fixed inset-0 bg-black/80 backdrop-blur-sm flex items-center justify-center z-50 animate-fade-in" 
      onClick={onClose}
    >
      <div 
        className="bg-nexus-surface/95 border border-nexus-accent/20 rounded-2xl w-full max-w-3xl h-[85vh] shadow-2xl shadow-nexus-accent/10 flex flex-col"
        onClick={(e) => e.stopPropagation()} // Modal içine tıklanınca kapanmasını engeller
      >
        <header className="flex items-center justify-between p-4 border-b border-gray-700 flex-shrink-0">
          <div>
            <h2 className="text-2xl font-bold text-nexus-accent glow-text">Interview Report</h2>
            <p className="text-gray-400">Topic: {interview.topic}</p>
          </div>
          <button 
            onClick={onClose} 
            className="p-2 rounded-full text-gray-400 hover:bg-gray-700 hover:text-white transition-colors"
            aria-label="Close report"
          >
            <X className="w-6 h-6" />
          </button>
        </header>

        <main className="flex-grow p-6 overflow-y-auto custom-scrollbar">
          <div className="markdown-content text-gray-300">
            {interview.feedback ? (
              <ReactMarkdown>{interview.feedback}</ReactMarkdown>
            ) : (
              <p>No feedback available for this session.</p>
            )}
          </div>
        </main>
        
        <footer className="p-4 border-t border-gray-700 flex-shrink-0 text-center">
            <p className="text-sm text-gray-500">
              Report generated by Nexus AI on {new Date(interview.completed_at || Date.now()).toLocaleDateString()}
            </p>
        </footer>
      </div>
    </div>
  );
};

export default InterviewReportModal;